global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'nexus-combined-receiver'

receivers:
  - name: 'nexus-combined-receiver'
    webhook_configs:
      - url: 'http://nexus-hub:3001/v1/webhook'
    email_configs:
      - to: 'singhaanimesh216@gmail.com'
        from: 'Nexus Monitoring <support@yoforex.net>'
        smarthost: 'smtp.hostinger.com:465'
        auth_username: 'support@yoforex.net'
        auth_password: 'Arijit@@101'
        require_tls: false # Port 465 uses Implicit SSL
